### ISSUE TITLE
Change wording around upgrade

### ISSUE THREAD

**Issue by ht2** [LearningLocker/deploy#15]
Had a comment from a user on Gitter that he thought pressing `n` at the upgrade question would _stop_ the install. Perhaps change wording to be clear that we are either upgrading or installing from scratch

**Comment by gardron** [comment]
Fixed the wording and added an explicit option to exit the script

**Comment by ht2** [comment]
Nice. Just referencing the commit here: 836327ad540ab1c6923148cc73d1302fcef06f8d
