### ISSUE TITLE
Intalling Learning Locker v2 in Amazon Linux AMI AWS

### ISSUE THREAD

**Issue by juesquis** [LearningLocker/deploy#22]
When i installing Learning Locker in AWs don't work, because he can't detect REDIS installation. Someone have can instaling Learning Locker v2 in this machine or in AWS?

**Comment by ht2** [comment]
As the message states in the script, that distro does not come with a version of Redis available through a repo. You have two options; use a different repo (e.g. Ubuntu 16) which does have it, or manually install (via make) Redis before running the script:

https://medium.com/@andrewcbass/install-redis-v3-2-on-aws-ec2-instance-93259d40a3ce
