### ISSUE TITLE
Unable to Transmit xAPI statement to Learning Locker 2.0 from Apache 

### ISSUE THREAD

**Issue by batcheej** [LearningLocker/deploy#28]
When trying to send a XAPI statement from Activity hosted on Apache , Cross Origin Requests to Learning Locker 2.0 are blocked.  Apache and Learning Locker 2.0 are on the same host. 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:3000/data/xAPI/statements. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:3000/data/xAPI/statements. (Reason: CORS request failed). <unknown>

**Comment by ht2** [comment]
Remove the `:3000` from your URL

**Comment by ht2** [comment]
Please submit this issue to the https://github.com/LearningLocker/learninglocker following our [New Issues Guidelines](https://github.com/LearningLocker/learninglocker/issues/new)
