### ISSUE TITLE
Cant Start service - service not found

### ISSUE THREAD

**Issue by moneyhan** [LearningLocker/deploy#31]
Wondering why the service wont start.  Made it all the way through the install script without errors.  

Use `pm2 show <id|name>` to get more details about an app
[PM2] Saving current process list...
[PM2] Successfully saved in /usr/local/learninglocker/releases/.pm2/dump.pm2
Failed to restart pm2-learninglocker.service: Unit pm2-learninglocker.service not found.
[LL] PM2 processes restarted
[LL] restarting nginx....
[LL] cleaning up temp directories
root@QC-SRV-001:/home/mmonahan# service pm2-learninglocker restart
Failed to restart pm2-learninglocker.service: Unit pm2-learninglocker.service not found.
root@QC-SRV-001:/home/mmonahan# 

Any ideas?

Thanks

**Comment by ht2** [comment]
Looking at the chat it seems as if this was due to you not running the script as the root user. I'll close this out
