### ISSUE TITLE
fatal: repository 'https://github.com/LearningLocker/learninglocker_node/' not found

### ISSUE THREAD

**Issue by positively** [LearningLocker/deploy#39]
https://github.com/LearningLocker/deploy/blob/62468a096e95c4cc1817ddf7b0cdc1f834d9f219/llv2_build.sh#L397

**Comment by positively** [comment]
> ENTERPRISE=true
> # if true then do things specific to enterprise (ie: don't set up mongo or redis).
> # this is designed to be mostly the same as the OS model so search for this variable to see differences
I need to install redis but not mongodb with LL.. How can I gain this result? I got error above...

**Comment by gardron** [comment]
Enterprise mode is not supported for the opensource install, it's something we use for our internal deployment. You shouldn't be setting it basically as it isn't supported without authentication credentials

**Comment by gardron** [comment]
If you run the install script as normal it'll ask you in turn if you want to install redis and mongo - you can pick each one independently
