### ISSUE TITLE
can't copy directory '/tmp/learninglocker/webapp/node_modules' as it doesn't exist- exiting

### ISSUE THREAD

**Issue by pradeeprohith** [LearningLocker/deploy#49]
i am not able to install the packages and getting this issue in ubuntu17.10

**Comment by gardron** [comment]
This is down to an installation problem locally to your install - I'm closing the ticket but if it keeps occuring then please attach /var/log/learninglocker/install.log so we can see what is happening

**Comment by djoudi** [comment]
i have the same issue with ubunutu 18.04
