### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ekinsenler** [LearningLocker/deploy#54]
Hello,
I am using Ubuntu 18.04.
I tried to install via both script. But I couldn't really get through the part of installation of nodejs. I get the following error message every time:
[LL] Installing node version: 6.x
[LL] Something went wrong in installing/updating nodejs. This is likely a fault in your apt config. Can't continue
Are there any pre installation requirement that I had to be done?

**Comment by T-G-G** [comment]
Can recreate using a [VM Ubuntu 16.04](https://app.vagrantup.com/ubuntu/boxes/xenial64) image and the latest deployll.sh.

**Comment by T-G-G** [comment]
Upgrading the Ubuntu version to 16.04.5 seems to default to installing node version 8.x which seemed to do the trick and gets past this part of the installation.

**Comment by rahimseyidovduisburg** [comment]
I installed ubuntu 18 and could use the script provided on the website to install the whole thing. However, xAPI did not work. It shows errored status in pm2. Need to figure out why

**Comment by Grechanin** [comment]
> I installed ubuntu 18 and could use the script provided on the website to install the whole thing. However, xAPI did not work. It shows errored status in pm2. Need to figure out why

the same
@rahimseyidovduisburg Have you resolved?
