### ISSUE TITLE
/tmp/learninglocker/webapp/node_modules doesn't exist. 

### ISSUE THREAD

**Issue by zoltanracskay** [LearningLocker/deploy#64]
Hi,

I try to use the install script provided on your website to install LearningLocker 2 on Jetson Nano, arm7 single board computer running Ubuntu 18.04. When running the standard install script I get the error message as in the title of the issue.

My question would be: How can I solve the problem, so LL2  can run on my device. Memory is 4Gb background storage is 250Gb.

Thank you Zoltan

**Comment by zoltanracskay** [comment]
![Screenshot from 2020-04-01 10-35-38](https://user-images.githubusercontent.com/23723286/78116904-420c9200-7405-11ea-920f-31ab00d6114c.png)

**Comment by djoudi** [comment]
i have the same issues

**Comment by asahd** [comment]
Hey @zoltanracskay [sorry that I didn't see this earlier], @djoudi 

I'd imagine this is because `/tmp` does not allow execution on your installations.

How does it work with the attached script? (You should remove `.txt` from the end before running)
[deployll_noTmp.sh.txt](https://github.com/LearningLocker/deploy/files/4538835/deployll_noTmp.sh.txt)

**Comment by djoudi** [comment]
@asahd 
after test 
i see this error 

https://i.imgur.com/YiNQSZl.png

**Comment by djoudi** [comment]
![image](https://user-images.githubusercontent.com/152725/80401786-3655a380-88bd-11ea-887a-568d136dbb49.png)

**Comment by asahd** [comment]
Hey @djoudi - Oops

I've updated the script in my last post, can you re-download and try again?

I've tested it myself and it seems to work nicely now

**Comment by djoudi** [comment]
hi @asahd  sorry see this issue 
![image](https://user-images.githubusercontent.com/152725/80504892-e8e83d80-8973-11ea-99e0-ef2e36bf9c4d.png)


https://i.imgur.com/yz5piI6.png

**Comment by asahd** [comment]
Okay, there is something else wrong with your server then

@djoudi Can you upload the file `/var/log/learninglocker/install.log` here?

**Comment by djoudi** [comment]
@asahd  see this 

`current node version is found as v10
[LL] Node.js already installed
[LL] node version - v10.20.1
[LL] yarn already installed
[LL] Running install steps
[LL] Git version: 2.17.1, minimum: 1.7.10
[LL] Will now try and clone the git repo for the main learninglocker software. May take some time....
running git clone
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
Le paquet « cmdtest » n'est pas installé, et ne peut donc être supprimé
0 mis à jour, 0 nouvellement installés, 0 à enlever et 2 non mis à jour.
no webapp dir after git - problem
[LL] Copied example env to .env - This will need editing by hand
[LL] checking UnicodeData is present...
[LL] the path for the unicode file wasn't passed to unicode_definition_install correctly (/root/learninglocker/webapp/UnicodeData.txt)
done!
[LL] running yarn install....
yarn install v1.5.1
error An unexpected error occurred: "Invalid value type 2:0 in /root/learninglocker/webapp/.yarnrc".
info If you think this is a bug, please open a bug report with the information provided in "/root/learninglocker/webapp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
done!
[LL] adding pm2....
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/bin/pm2-docker -> /usr/lib/node_modules/pm2/bin/pm2-docker
/usr/bin/pm2-runtime -> /usr/lib/node_modules/pm2/bin/pm2-runtime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pm2@4.4.0
updated 1 package in 10.113s
done!
[LL] running yarn build-all (this can take a little while - don't worry, it's not broken)....
yarn run v1.5.1
error An unexpected error occurred: "Invalid value type 2:0 in /root/learninglocker/webapp/.yarnrc".
info If you think this is a bug, please open a bug report with the information provided in "/root/learninglocker/webapp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
done!
[LL] installing pm2 logrotate....
[PM2][Module] Installing NPM pm2-logrotate module
[PM2][Module] Module already installed. Updating.
[PM2] Applying action deleteProcessId on app [0](ids: 0)
[PM2] [pm2-logrotate](0) ✓
In memory process deleted
Deleteing /root/.pm2/modules/pm2-logrotate
[PM2][Module] Calling [NPM] to install pm2-logrotate ...
+ pm2-logrotate@2.7.0
added 292 packages from 257 contributors and audited 657 packages in 9.52s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[PM2][Module] Module downloaded
[PM2][WARN] Applications pm2-logrotate not running, starting...
[PM2] App [pm2-logrotate] launched (1 instances)
Module: pm2-logrotate
$ pm2 set pm2-logrotate:max_size 10M
$ pm2 set pm2-logrotate:retain 30
$ pm2 set pm2-logrotate:compress true
$ pm2 set pm2-logrotate:dateFormat YYYY-MM-DD_HH-mm-ss
$ pm2 set pm2-logrotate:workerInterval 30
$ pm2 set pm2-logrotate:rotateInterval 0 0 * * *
$ pm2 set pm2-logrotate:rotateModule true
Modules configuration. Copy/Paste line to edit values.
[PM2][Module] Module successfully installed and launched
[PM2][Module] Checkout module options: `$ pm2 conf`
┌─────┬──────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name             │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└─────┴──────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Module
┌────┬───────────────────────────────────────┬────────────────────┬───────┬──────────┬──────┬──────────┬──────────┬──────────┐
│ id │ module                                │ version            │ pid   │ status   │ ↺    │ cpu      │ mem      │ user     │
├────┼───────────────────────────────────────┼────────────────────┼───────┼──────────┼──────┼──────────┼──────────┼──────────┤
│ 0  │ pm2-logrotate                         │ 2.7.0              │ 11698 │ online   │ 0    │ 0%       │ 18.8mb   │ root     │
└────┴───────────────────────────────────────┴────────────────────┴───────┴──────────┴──────┴──────────┴──────────┴──────────┘
done!
[LL] setting up pm2 logrotate....
[PM2] Module pm2-logrotate restarted
[PM2] Setting changed
Module: pm2-logrotate
$ pm2 set pm2-logrotate:max_size 10M
$ pm2 set pm2-logrotate:retain 30
$ pm2 set pm2-logrotate:compress true
$ pm2 set pm2-logrotate:dateFormat YYYY-MM-DD_HH-mm-ss
$ pm2 set pm2-logrotate:workerInterval 30
$ pm2 set pm2-logrotate:rotateInterval 0 0 * * *
$ pm2 set pm2-logrotate:rotateModule true
done!
[LL] Will now try and clone the git repo for XAPI. May take some time....
attempting git clone for xapi, branch: master
git clone succeeded
[LL] Copied example env to .env - This will need editing by hand
[LL] running yarn install....
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@ht2-labs/semantic-release > semantic-release-docker@2.2.0" has incorrect peer dependency "semantic-release@>=11.0.0 <16.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 10.18s.
done!
[LL] running yarn build....
yarn run v1.5.1
$ tsc
Done in 15.05s.
done!
[LL] creating /root/.tmpdist
[LL] copying modules....
can't copy directory '/root/learninglocker/webapp/node_modules' as it doesn't exist- exiting
`

**Comment by asahd** [comment]
@djoudi Yeah, the install of the packages fails for the `webapp` folder, so the error makes sense

```[LL] running yarn install....
yarn install v1.5.1
error An unexpected error occurred: "Invalid value type 2:0 in /root/learninglocker/webapp/.yarnrc".```

The version of Yarn being used is quite old (`v1.5.1`), the install script should install the latest version (I've tried this and it installs `v1.22.4`) but if it sees that yarn is already installed, it will not install a newer version.

Please try manually updating the Yarn version, clear the files made by the script (`/root/learninglocker` folder) and try again:
https://classic.yarnpkg.com/en/docs/install#debian-stable
